# -*- coding: UTF-8 -*-

# Build customizations
# Change this file instead of sconstruct or manifest files, whenever possible.

_ = lambda x: x

# Full add-on dictionary, to build manifest and add-on plural tags
addon_info = {
    # add-on Name, internal for nvda
    "addon_name": "BOA",
    # Add-on summary, usually the user visible name of the addon.
    "addon_summary": "BOA: Better Office Accessibility",
    # Add-on description
    "addon_description": _("""A powerful suite of accessibility enhancements for Microsoft Office, designed to vastly improve the screen reader experience for NVDA users. 
    
    Key Features:
    - Cell Monitor: Save and continuously track dynamic Excel cells.
    - Sheet Layout Analyzer: Instantly scan worksheets for hidden tabs, protected states, and data blocks.
    - Bulk Sheet Organizer & Quick Mover: Instantly move or reorder multiple sheets using accessible dialogs.
    - PowerPoint Color Pickers: Read hidden Hex and RGB codes inside standard color grids.
    
    Please refer to the add-on help documentation for a complete list of features and shortcuts."""),
    "addon_version": "2.0",
    # Author(s)
    "addon_author": "MisterK with Anti Gravity2 <ravana.krn@gmail.com>",
    # URL for the add-on documentation support
    "addon_url": "https://github.com/MisterK-Dev/BOA-Better-Office-Accessibility-with-NVDA",
    # URL for the add-on repository where the source code is hosted
    "addon_sourceURL": "https://github.com/MisterK-Dev/BOA-Better-Office-Accessibility-with-NVDA",
    # Documentation file name
    "addon_docFileName": "readme.html",
    # Minimum NVDA version supported
    "addon_minimumNVDAVersion": "2026.1.0",
    # Last NVDA version supported/tested
    "addon_lastTestedNVDAVersion": "2026.1.1",
    # True if the addon requires an update to the manifest format.
    "addon_updateChannel": None,
    # Changelog URL or None
    "addon_changelog": _("""## What's New in v1.6.1
* **Deep File Localization**: Fixed missing string translations deep within the Excel enhancement modules (such as the Sheet Layout Analyzer and Quick Sheet Mover) to ensure 100% localization coverage.
* **Expanded Translation Support**: Added 7 new languages to the system (Turkish, Polish, Korean, Ukrainian, Czech, Urdu, and Punjabi). 
  *(Note: These translations were generated by AI, so some minor translation errors or inaccuracies may be present.)*"""),
}

# Define the python files that are the sources of your add-on.
# You can either list every file (using ""/") as a path separator,
# or use glob expressions.
pythonSources = [
    "addon/globalPlugins/*.py", 
    "addon/appModules/*.py",
    "addon/appModules/boa_enhancements/*.py",
    "addon/appModules/boa_enhancements/excel_enhancements/*.py",
    "addon/appModules/boa_enhancements/powerpoint_enhancements/*.py",
    "addon/appModules/boa_enhancements/word_enhancements/*.py",
    "addon/appModules/boa_enhancements/ui/*.py"
]

# Files that contain strings for translation. Usually your python sources
i18nSources = pythonSources + ["buildVars.py"]

# Files that will be ignored when building the nvda-addon file
# Paths are relative to the addon directory, not to the root directory of your addon sources.
excludedFiles = []

# Base language for the NVDA add-on
# If your add-on is written in a language other than english, modify this variable.
# For example, set baseLanguage to "es" if your add-on is primarily written in spanish.
baseLanguage = "en"

# Markdown extensions for add-on documentation
# Most add-ons do not require additional Markdown extensions.
# If you need to add support for markup such as tables, fill out the below list.
# Extensions string must be of the format "markdown.extensions.extensionName"
# e.g. "markdown.extensions.tables" to add tables.
markdownExtensions = ["markdown.extensions.tables"]

# Added for SCons compatibility
brailleTables = []
symbolDictionaries = []
speechDictionaries = []
