import os
import json
import glob

# Gather all translations
translations = {}
for i in range(1, 6):
    batch_file = f"scratch/batch{i}.json"
    if os.path.exists(batch_file):
        with open(batch_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
            translations.update(data)

en_changelog = "### What's New in v1.6.1\n* **Deep File Localization**: Fixed missing string translations deep within the Excel enhancement modules (such as the Sheet Layout Analyzer and Quick Sheet Mover) to ensure 100% localization coverage.\n* **Expanded Translation Support**: Added 7 new languages to the system (Turkish, Polish, Korean, Ukrainian, Czech, Urdu, and Punjabi). \n  *(Note: These translations were generated by AI, so some minor translation errors or inaccuracies may be present.)*"

for lang, trans_dict in translations.items():
    readme_path = os.path.join("addon", "doc", lang, "readme.md")
    if not os.path.exists(readme_path):
        continue
        
    with open(readme_path, 'r', encoding='utf-8') as f:
        content = f.read()
        
    translated_cl = ""
    # Find the translated changelog for this language
    for k, v in trans_dict.items():
        if "v1.6.1" in k and "Deep File Localization" in k:
            translated_cl = v.replace('\\n', '\n')
            break
            
    if not translated_cl:
        continue
        
    # The JSON dict has "## What's New in v1.6.1". Let's change it to "### " to match English markdown hierarchy
    if translated_cl.startswith("## ") and not translated_cl.startswith("### "):
        translated_cl = "#" + translated_cl

    # Also, some might have ## v1.6.1 or similar. Let's make sure translated_cl has correct heading
    
    # 1. First, let's remove the translated changelog if it's appended at the VERY BOTTOM of the file
    # Or anywhere actually, because we will re-insert it properly.
    if translated_cl in content:
        content = content.replace("\n\n" + translated_cl + "\n", "")
        content = content.replace("\n\n" + translated_cl, "")
        content = content.replace("\n" + translated_cl, "")
        content = content.replace(translated_cl, "")
        
    # Also remove if it was with "## " (before we added the "#")
    orig_translated_cl = translated_cl[1:] if translated_cl.startswith("### ") else translated_cl
    if orig_translated_cl in content:
        content = content.replace("\n\n" + orig_translated_cl + "\n", "")
        content = content.replace("\n\n" + orig_translated_cl, "")
        content = content.replace("\n" + orig_translated_cl, "")
        content = content.replace(orig_translated_cl, "")
        
    # Also strip any trailing whitespace/newlines from the end to be clean
    content = content.rstrip() + "\n"
    
    # Now insert it in the correct spot.
    # Case A: English block is present (e.g. 7 new languages copied from en/readme.md)
    if en_changelog in content:
        content = content.replace(en_changelog, translated_cl)
    else:
        # Case B: For the old 17 languages, the English block is NOT present.
        # Find the line that starts with "## 🛠️" and insert immediately after it.
        lines = content.split('\n')
        insert_idx = -1
        for i, line in enumerate(lines):
            if line.startswith("## 🛠️"):
                insert_idx = i + 1
                break
                
        if insert_idx != -1:
            # If there's an empty line after the header, skip it
            if insert_idx < len(lines) and lines[insert_idx].strip() == "":
                insert_idx += 1
            
            lines.insert(insert_idx, translated_cl + "\n")
            content = "\n".join(lines)
            
    # Save the file
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print(f"Fixed {lang}/readme.md")
