import os
import re
import shutil
import polib
import time
from deep_translator import GoogleTranslator

# NVDA language codes to Google Translate codes
lang_map = {
    "es": "es", "fr": "fr", "de": "de", "pt": "pt", "zh_CN": "zh-CN",
    "ja": "ja", "ru": "ru", "ar": "ar", "it": "it", "tr": "tr",
    "pl": "pl", "ko": "ko", "uk": "uk", "cs": "cs", "hi": "hi",
    "ta": "ta", "te": "te", "mr": "mr", "bn": "bn", "kn": "kn",
    "gu": "gu", "ml": "ml", "ur": "ur", "pa": "pa"
}

def translate_safe(text, dest_lang):
    if not text.strip():
        return text
        
    # Extract {variables}
    placeholders = re.findall(r'\{[^\}]+\}', text)
    temp_text = text
    for i, p in enumerate(placeholders):
        temp_text = temp_text.replace(p, f" X{i}X ")
        
    try:
        translator = GoogleTranslator(source='en', target=dest_lang)
        # Handle newlines by splitting and translating if it's too long, but BOA strings are short
        translated = translator.translate(temp_text)
        
        # Restore variables
        for i, p in enumerate(placeholders):
            # Regex to find X{i}X with optional spaces around it
            translated = re.sub(rf'\s*X{i}X\s*', p, translated)
            
        return translated
    except Exception as e:
        print(f"Error translating '{text}': {e}")
        return text # fallback to english

def parse_po(filepath):
    if not os.path.exists(filepath):
        return []
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    msgids = []
    lines = content.split('\n')
    current_msgid = ""
    in_msgid = False
    
    for line in lines:
        if line.startswith('msgid '):
            in_msgid = True
            current_msgid = line[6:].strip().strip('"')
        elif line.startswith('msgstr '):
            if current_msgid and current_msgid != "":
                msgids.append(current_msgid)
            in_msgid = False
            current_msgid = ""
        elif in_msgid and line.startswith('"'):
            current_msgid += line.strip().strip('"')
    return msgids

def main():
    pot_file = "BOA.pot"
    pot_po = polib.pofile(pot_file)
    pot_ids = parse_po(pot_file)
    
    changelog_id = "## What's New in v1.6.1\n* **Deep File Localization**: Fixed missing string translations deep within the Excel enhancement modules (such as the Sheet Layout Analyzer and Quick Sheet Mover) to ensure 100% localization coverage.\n* **Expanded Translation Support**: Added 7 new languages to the system (Turkish, Polish, Korean, Ukrainian, Czech, Urdu, and Punjabi). \n  *(Note: These translations were generated by AI, so some minor translation errors or inaccuracies may be present.)*"
    
    for lang, g_code in lang_map.items():
        print(f"\n--- Processing {lang} ---")
        locale_dir = os.path.join("addon", "locale", lang, "LC_MESSAGES")
        os.makedirs(locale_dir, exist_ok=True)
        po_path = os.path.join(locale_dir, "nvda.po")
        
        if os.path.exists(po_path):
            po = polib.pofile(po_path)
            po_ids = parse_po(po_path)
        else:
            po = polib.pofile(pot_file)
            for entry in po:
                entry.msgstr = ""
            po_ids = []
            
        po.metadata['Language'] = lang
        po.metadata['Content-Type'] = 'text/plain; charset=UTF-8'
        po.metadata['Content-Transfer-Encoding'] = '8bit'
        if 'fuzzy' in po.metadata:
            del po.metadata['fuzzy']
            
        missing = [m for m in pot_ids if m not in po_ids]
        if not missing:
            print(f"{lang} is fully translated.")
            continue
            
        print(f"Translating {len(missing)} strings for {lang}...")
        
        translated_changelog = ""
        updated = 0
        
        for entry in po:
            if entry.msgid in missing:
                trans = translate_safe(entry.msgid, g_code)
                entry.msgstr = trans
                if 'fuzzy' in entry.flags:
                    entry.flags.remove('fuzzy')
                updated += 1
                
                if entry.msgid == changelog_id:
                    translated_changelog = trans
                    
                time.sleep(0.1) # prevent rate limiting
                
        po.save(po_path)
        print(f"Saved {updated} translations to {po_path}")
        
        # Readme injection
        doc_dir = os.path.join("addon", "doc", lang)
        os.makedirs(doc_dir, exist_ok=True)
        readme_path = os.path.join(doc_dir, "readme.md")
        
        en_readme = os.path.join("addon", "doc", "en", "readme.md")
        
        if not os.path.exists(readme_path):
            if os.path.exists(en_readme):
                shutil.copy(en_readme, readme_path)
                print(f"Created new {lang} readme.md")
                
        if translated_changelog:
            with open(readme_path, 'r', encoding='utf-8') as f:
                content = f.read()
            if "v1.6.1" not in content and translated_changelog:
                with open(readme_path, 'a', encoding='utf-8') as f:
                    f.write(f"\n\n{translated_changelog}\n")
                print(f"Appended translated changelog to {lang} readme.md")

if __name__ == '__main__':
    main()
