import os
import json
import polib
import shutil

def process_batch(json_file):
    with open(json_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    pot_path = "BOA.pot"
    if not os.path.exists(pot_path):
        print("BOA.pot not found!")
        return
        
    for lang, translations in data.items():
        print(f"Processing language: {lang}")
        
        locale_dir = os.path.join("addon", "locale", lang, "LC_MESSAGES")
        os.makedirs(locale_dir, exist_ok=True)
        po_path = os.path.join(locale_dir, "nvda.po")
        
        if os.path.exists(po_path):
            po = polib.pofile(po_path)
        else:
            po = polib.pofile(pot_path)
            for entry in po:
                entry.msgstr = ""
            
        po.metadata['Language'] = lang
        po.metadata['Content-Type'] = 'text/plain; charset=UTF-8'
        po.metadata['Content-Transfer-Encoding'] = '8bit'
        if 'fuzzy' in po.metadata:
            del po.metadata['fuzzy']
            
        updated_count = 0
        added_count = 0
        for msgid, msgstr in translations.items():
            # Fix the literal \\n back to \n since JSON dump might have escaped it,
            # or my python dict had "\\n". The POT has actual newlines.
            real_msgid = msgid.replace('\\n', '\n')
            real_msgstr = msgstr.replace('\\n', '\n')
            
            entry = po.find(real_msgid)
            if entry:
                entry.msgstr = real_msgstr
                if 'fuzzy' in entry.flags:
                    entry.flags.remove('fuzzy')
                updated_count += 1
            else:
                entry = polib.POEntry(msgid=real_msgid, msgstr=real_msgstr)
                po.append(entry)
                added_count += 1
                
        po.save(po_path)
        print(f"  - Updated {updated_count} and Added {added_count} strings in {lang}/nvda.po")
        
        # 2. Handle Readme
        doc_dir = os.path.join("addon", "doc", lang)
        os.makedirs(doc_dir, exist_ok=True)
        readme_path = os.path.join(doc_dir, "readme.md")
        
        if not os.path.exists(readme_path):
            en_readme = os.path.join("addon", "doc", "en", "readme.md")
            if os.path.exists(en_readme):
                shutil.copy(en_readme, readme_path)
                print(f"  - Created {lang}/readme.md from English template")
        else:
            # Append changelog
            changelog_id = "## What's New in v1.6.1\n* **Deep File Localization**: Fixed missing string translations deep within the Excel enhancement modules (such as the Sheet Layout Analyzer and Quick Sheet Mover) to ensure 100% localization coverage.\n* **Expanded Translation Support**: Added 7 new languages to the system (Turkish, Polish, Korean, Ukrainian, Czech, Urdu, and Punjabi). \n  *(Note: These translations were generated by AI, so some minor translation errors or inaccuracies may be present.)*"
            # It might have been escaped in json
            cl_key = changelog_id.replace('\n', '\\n')
            if cl_key in translations:
                translated_cl = translations[cl_key].replace('\\n', '\n')
                with open(readme_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                if "v1.6.1" not in content and translated_cl:
                    with open(readme_path, 'a', encoding='utf-8') as f:
                        f.write(f"\n\n{translated_cl}\n")
                    print(f"  - Appended translated v1.6.1 changelog to {lang}/readme.md")

if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1:
        process_batch(sys.argv[1])
    else:
        print("Usage: python update_translations.py <batch.json>")
